/**
 * @NApiVersion 2.0
 * @NScriptType UserEventScript
 */
define(['N/ui/serverWidget', 'N/record', 'N/search'],
    function(serverWidget, record, search) {
        function beforeLoad(context) {
          if (context.type === context.UserEventType.CREATE){
              var currentRecord = context.newRecord;
              var currentRecordId = context.newRecord.id;
              currentRecord.setValue({fieldId:'custbody_tc_special_instructions',value:'Delivery Appointment Required'})            
          }
          
            if (context.type === context.UserEventType.VIEW) {

               var currentRecordId = context.newRecord.id;
               var giive_alert;

                var transactionSearchObj = search.create({
                    type: "transaction",
                    filters: [
                        ["type", "anyof", "Custom116"],
                        "AND",
                        ["mainline", "is", "F"],
                        "AND",
                        ["custcol_tc_sales_order", "noneof", "@NONE@"],
                        "AND",
                        ["internalid", "anyof", currentRecordId], 
                        "AND", 
                        ["custcol_tc_sales_order.shipcity","isnotempty",""]
                    ],
                    columns: [
                        search.createColumn({
                          name: "formulatext",
                          formula: "LOWER({custcol_tc_sales_order.shipcity})",
                          summary: "GROUP",
                          label: "Shipping City"
                        }),
                        search.createColumn({
                            name: "type",
                            summary: "GROUP",
                            label: "Type"
                        })
                    ]
                });
                var searchResultCount = transactionSearchObj.runPaged().count;
                log.debug("transactionSearchObj result count", searchResultCount);
                transactionSearchObj.run().each(function(result) {
                  log.debug('result', result)

                    if (searchResultCount > 1) {
                      giive_alert = true;
                    }
                    return true;
                });


                    if(giive_alert){
                    var alert_value = "<html><body><div style='font-weight:bold;'>Alert ⚠: </div><script type='text/javascript'>window.alert('⚠ Alert ⚠: Multiple Shipping Locations Detected On This Record, Please Verify.');</script><div style='font-size:10px;'>- Generated by NetSuite User Event Script</div></body></html>";

                    var form = context.form;
                    var field = form.addField({
                        id: 'custpage_alertfield',
                        type: serverWidget.FieldType.INLINEHTML,
                        label: 'Alert Field'
                    });

                    field.defaultValue = alert_value;
                  }

            }
        }

        return {
            beforeLoad: beforeLoad
        };
    });
